# Use root/example as user/password credentials
version: '3.1'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ./symfony/:/var/www/symfony/
    ports:
      - 8001:80

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    environment:
      APP_ENV: dev
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9003 remote_connect_back=0
    volumes:
      - ./symfony/:/var/www/symfony/

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dev-db-api:/var/lib/mysql

volumes:
  dev-db-api:
